"""Dialectical Chain-of-Thought harness — v0.8.0.

Applies the v0.7.0 quantitative-dialectic protocol (thesis → antithesis →
synthesis with computed E[step correct]) at every step of a reasoning chain.

See `skills/dialectical-cot/SKILL.md` for the protocol specification and
`docs/theory.md` §3.12 for the theoretical framing (thought-loop as a
fourth LDD optimizer layer).

Core abstractions:
    CotLLMClient  — protocol for LLM-backed step proposing / attacking /
                    synthesizing. Users plug in their LLM; MockCotLLMClient
                    ships for testing.
    Step          — one step in the chain: thesis + antitheses + synthesis +
                    E[step correct] + decision (commit/revise/reject)
    CoTChain      — an in-progress or completed chain
    CoTRunner     — orchestrates the 5-step protocol per step of the chain
"""
from __future__ import annotations

import datetime as _dt
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Literal, Optional, Protocol, TYPE_CHECKING

if TYPE_CHECKING:
    from ldd_trace.store import TraceStore


# ---------------------------------------------------------------------------
# Decision thresholds (calibratable — see SKILL.md §Step-level decisions)
# ---------------------------------------------------------------------------

COMMIT_THRESHOLD = 0.70
REVISE_THRESHOLD = 0.40
MAX_BACKTRACKS = 3
DEFAULT_MAX_STEPS = 10


Decision = Literal["commit", "revise", "reject"]


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class Antithesis:
    """One counter-case against the current thesis.

    Source:
      "primer"       — drawn from memory (project_memory.json or cot_memory.json)
      "independent"  — generated by the LLM without primer hints (anti-groupthink)
    """

    source: Literal["primer", "independent"]
    content: str
    prob_applies: float
    impact: float
    provenance: str = ""  # for primers: which memory signal; for independent: prompt hint


@dataclass
class Step:
    """One step in the chain — the full dialectical pass at position k."""

    k: int
    task_type: str
    thesis: str
    thesis_prior: float
    antitheses: List[Antithesis] = field(default_factory=list)
    synthesis: str = ""
    predicted_correct: float = 0.0
    decision: Decision = "commit"
    tokens: int = 0
    timestamp: str = ""

    def to_dict(self) -> dict:
        return {
            "k": self.k,
            "task_type": self.task_type,
            "thesis": self.thesis,
            "thesis_prior": round(self.thesis_prior, 4),
            "antitheses": [
                {
                    "source": a.source,
                    "content": a.content,
                    "prob_applies": round(a.prob_applies, 4),
                    "impact": round(a.impact, 4),
                    "provenance": a.provenance,
                }
                for a in self.antitheses
            ],
            "synthesis": self.synthesis,
            "predicted_correct": round(self.predicted_correct, 4),
            "decision": self.decision,
            "tokens": self.tokens,
            "timestamp": self.timestamp,
        }


@dataclass
class CoTChain:
    """A chain of reasoning steps, in-progress or completed."""

    task: str
    task_type: str
    ground_truth: Optional[str] = None
    steps: List[Step] = field(default_factory=list)
    final_answer: Optional[str] = None
    predicted_chain_correct: Optional[float] = None
    actual_correct: Optional[bool] = None
    total_tokens: int = 0
    backtrack_count: int = 0
    terminal: Literal["complete", "partial", "failed", "aborted"] = "partial"
    started_at: str = ""
    ended_at: str = ""

    def to_dict(self) -> dict:
        return {
            "task": self.task,
            "task_type": self.task_type,
            "ground_truth": self.ground_truth,
            "steps": [s.to_dict() for s in self.steps],
            "final_answer": self.final_answer,
            "predicted_chain_correct": (
                round(self.predicted_chain_correct, 4)
                if self.predicted_chain_correct is not None
                else None
            ),
            "actual_correct": self.actual_correct,
            "total_tokens": self.total_tokens,
            "backtrack_count": self.backtrack_count,
            "terminal": self.terminal,
            "started_at": self.started_at,
            "ended_at": self.ended_at,
        }


# ---------------------------------------------------------------------------
# LLM protocol — user plugs in their LLM; MockCotLLMClient for tests
# ---------------------------------------------------------------------------


@dataclass
class ProposedStep:
    """Output of propose_step — the thesis plus the LLM's self-rated prior."""

    content: str
    prior: float  # LLM's self-assessed probability the step is correct, in [0, 1]
    tokens: int = 0


@dataclass
class SynthesisOutput:
    """Output of synthesize — the revised step content + predicted_correct + decision."""

    content: str
    predicted_correct: float
    decision: Decision
    tokens: int = 0


class CotLLMClient(Protocol):
    """LLM-backed interface for the dialectical-CoT harness.

    Users implement this against their LLM of choice. `MockCotLLMClient`
    provides a deterministic test stub.
    """

    def propose_step(
        self,
        task: str,
        task_type: str,
        chain: List[Step],
    ) -> ProposedStep:
        ...

    def attack_step(
        self,
        task: str,
        thesis: str,
        chain: List[Step],
        skip_primers: bool = False,
    ) -> List[Antithesis]:
        ...

    def synthesize(
        self,
        thesis: str,
        thesis_prior: float,
        antitheses: List[Antithesis],
    ) -> SynthesisOutput:
        ...

    def is_answer_reached(self, chain: List[Step]) -> bool:
        ...

    def extract_answer(self, chain: List[Step]) -> str:
        ...

    def verify_answer(
        self,
        answer: str,
        ground_truth: Optional[str],
    ) -> Optional[bool]:
        ...


# ---------------------------------------------------------------------------
# Bayesian synthesis math — centralized so caller and tests agree
# ---------------------------------------------------------------------------


def compute_predicted_correct(
    thesis_prior: float,
    antitheses: List[Antithesis],
) -> float:
    """Compute E[step correct] given thesis prior and antitheses.

    Formula (v0.7.0 adapted for step correctness):
        E[correct] = (1 − Σ Pr(antithesis_i applies)) × thesis_prior
                   + Σ Pr(antithesis_i applies) × (thesis_prior + impact_i)

    Impact is the change to the step's correctness if the antithesis applies.
    Negative impact = regression (antithesis points out the step is wrong);
    positive impact = antithesis is spurious / favorable.

    Clamped to [0.0, 1.0].
    """
    if not antitheses:
        return max(0.0, min(1.0, thesis_prior))
    total_pr = sum(a.prob_applies for a in antitheses)
    # Expected correctness when no antithesis applies
    base = max(0.0, 1.0 - total_pr) * thesis_prior
    # Expected correctness when each antithesis applies
    conditional = sum(
        a.prob_applies * max(0.0, min(1.0, thesis_prior + a.impact))
        for a in antitheses
    )
    return max(0.0, min(1.0, base + conditional))


def decide_from_predicted(predicted: float) -> Decision:
    if predicted >= COMMIT_THRESHOLD:
        return "commit"
    if predicted >= REVISE_THRESHOLD:
        return "revise"
    return "reject"


# ---------------------------------------------------------------------------
# Primer integration — reuses v0.6.0 prime_antithesis when TraceStore available
# ---------------------------------------------------------------------------


def gather_primers(
    thesis: str,
    task_type: str,
    chain: List[Step],
    store: Optional["TraceStore"] = None,
) -> List[Antithesis]:
    """Pull antithesis primers from project memory + cot memory.

    Two sources:
      1. General project memory (v0.5.2): skill-effectiveness, plateau patterns
         — via `prime_antithesis`. Less directly applicable to CoT steps but
         surfaces general "this project has bad-patterns of type X" signal.
      2. CoT-specific memory (this module): per-task-type step effectiveness,
         common failure modes — see `cot_memory.py::cot_primers_for_task_type`.

    Converts each primer source into `Antithesis(source="primer", ...)`.
    """
    primers: List[Antithesis] = []

    if store is None:
        return primers

    # Source 1 — general project memory (v0.6.0 prime_antithesis output)
    try:
        from ldd_trace.aggregator import read_memory
        from ldd_trace.dialectical_prime import prime_antithesis

        project_memory = read_memory(store)
        if project_memory is not None:
            # Thesis text wrapped as a thesis-string; current-task context omitted
            # (CoT runs in a separate lifecycle from inner-loop iterations).
            material = prime_antithesis(
                memory=project_memory,
                thesis=f"CoT step: {thesis}",
                current=None,
                files=None,
                store=store,
            )
            for p in material.primers:
                # Project-memory primers are narrative — convert to numeric
                # antithesis with conservative heuristics. The harness caller
                # (MockCotLLMClient or real) can override these if the LLM
                # returns richer numbers.
                primers.append(
                    Antithesis(
                        source="primer",
                        content=p.material,
                        prob_applies=0.3,  # conservative default
                        impact=-0.15 if p.severity in ("warn", "high") else -0.05,
                        provenance=f"project_memory/{p.source}",
                    )
                )
    except Exception:  # pragma: no cover — graceful: no project memory is OK
        pass

    # Source 2 — CoT-specific memory (.ldd/cot_memory.json)
    try:
        from ldd_trace.cot_memory import cot_primers_for_task_type

        cot_primers = cot_primers_for_task_type(store, task_type=task_type)
        primers.extend(cot_primers)
    except Exception:  # pragma: no cover
        pass

    return primers


# ---------------------------------------------------------------------------
# The runner — orchestrates the 5-step protocol per step of the chain
# ---------------------------------------------------------------------------


class CoTRunner:
    """Dialectical-CoT orchestrator.

    Usage:
        runner = CoTRunner(llm=MyLLMClient(), store=TraceStore("."))
        chain = runner.run(
            task="What is 17 * 23?",
            task_type="math",
            ground_truth="391",
            max_steps=10,
        )

    Chain is logged to `.ldd/cot_traces.jsonl` and contributes to the
    per-task-type aggregate in `.ldd/cot_memory.json` after completion.
    """

    def __init__(
        self,
        llm: CotLLMClient,
        store: Optional["TraceStore"] = None,
        commit_threshold: float = COMMIT_THRESHOLD,
        revise_threshold: float = REVISE_THRESHOLD,
        max_backtracks: int = MAX_BACKTRACKS,
        trust_guard: Optional["Any"] = None,
        require_antithesis: bool = True,
    ) -> None:
        """v0.9.1: `trust_guard` sanitizes agent-supplied prior + antitheses
        per audit findings C2 / H1. `require_antithesis` (default True)
        rejects steps with zero antitheses to close the C2 bypass.
        """
        self.llm = llm
        self.store = store
        self.commit_threshold = commit_threshold
        self.revise_threshold = revise_threshold
        self.max_backtracks = max_backtracks
        self.require_antithesis = require_antithesis
        if trust_guard is None:
            from ldd_trace.trust_guard import default_trust_guard
            trust_guard = default_trust_guard
        self.trust_guard = trust_guard

    def run(
        self,
        task: str,
        task_type: str = "general",
        ground_truth: Optional[str] = None,
        max_steps: int = DEFAULT_MAX_STEPS,
    ) -> CoTChain:
        chain = CoTChain(
            task=task,
            task_type=task_type,
            ground_truth=ground_truth,
            started_at=_utcnow_iso(),
        )

        k = 0
        while k < max_steps:
            step = self._run_step(chain, k)
            if step is None:
                # backtrack path — chain.steps was mutated in-place
                if chain.backtrack_count > self.max_backtracks:
                    chain.terminal = "partial"
                    break
                k = len(chain.steps)
                continue

            chain.steps.append(step)
            chain.total_tokens += step.tokens

            if self.llm.is_answer_reached(chain.steps):
                chain.final_answer = self.llm.extract_answer(chain.steps)
                break

            k += 1
        else:
            chain.terminal = "partial"

        # Chain-level calibration — multiply per-step predicted correctness
        if chain.steps:
            chain.predicted_chain_correct = 1.0
            for s in chain.steps:
                chain.predicted_chain_correct *= s.predicted_correct

        # Verify against ground truth if available
        if chain.final_answer is not None:
            verified = self.llm.verify_answer(chain.final_answer, ground_truth)
            chain.actual_correct = verified
            if verified is True:
                chain.terminal = "complete"
            elif verified is False:
                chain.terminal = "failed"
            # verified is None → terminal stays as-is

        chain.ended_at = _utcnow_iso()

        # Persist + aggregate
        if self.store is not None:
            self._persist_chain(chain)

        return chain

    def _run_step(
        self,
        chain: CoTChain,
        k: int,
    ) -> Optional[Step]:
        """Run one dialectical-CoT step. Returns Step or None if backtracked."""
        # --- Step 1: thesis ---
        proposed = self.llm.propose_step(
            task=chain.task, task_type=chain.task_type, chain=chain.steps
        )
        # v0.9.1 P1 — cap prior (C2 fix): prevent LLM always-confident bypass
        safe_prior = self.trust_guard.guard_prior(proposed.prior)

        # --- Step 2: antitheses (primers + independent) ---
        primers = gather_primers(
            thesis=proposed.content,
            task_type=chain.task_type,
            chain=chain.steps,
            store=self.store,
        )
        independent = self.llm.attack_step(
            task=chain.task,
            thesis=proposed.content,
            chain=chain.steps,
            skip_primers=True,
        )
        antitheses = primers + independent

        # v0.9.1 P1 — validate antitheses bounds (H1 fix) + require ≥ 1 (C2 fix)
        # When require_antithesis is True AND primers is empty AND llm returned
        # nothing, the guard raises AntithesisAbsentError. Caller-level policy:
        # we catch it here and mark the chain terminal=antithesis-absent via
        # a soft-land (instead of crashing the chain).
        from ldd_trace.trust_guard import AntithesisAbsentError
        try:
            antitheses = self.trust_guard.guard_antitheses(
                antitheses, allow_empty=not self.require_antithesis
            )
        except AntithesisAbsentError:
            # Chain cannot continue — mark partial termination
            chain.terminal = "partial"  # will be confirmed by outer loop
            # Return a degenerate step so the chain records the event
            return Step(
                k=k, task_type=chain.task_type,
                thesis=proposed.content, thesis_prior=safe_prior,
                antitheses=[], synthesis=proposed.content,
                predicted_correct=0.0, decision="reject",
                tokens=proposed.tokens, timestamp=_utcnow_iso(),
            )

        # --- Step 3: synthesis ---
        synth = self.llm.synthesize(
            thesis=proposed.content,
            thesis_prior=safe_prior,
            antitheses=antitheses,
        )

        # Authoritative math — trust our formula over whatever the LLM says
        computed_predicted = compute_predicted_correct(
            thesis_prior=safe_prior, antitheses=antitheses
        )
        decision = decide_from_predicted(computed_predicted)

        # --- Step 4: decision ---
        if decision == "reject":
            # Backtrack: drop last step (if any) and retry
            chain.backtrack_count += 1
            if chain.steps:
                chain.steps.pop()
            return None

        synthesis_content = (
            synth.content if decision == "revise" else proposed.content
        )

        # --- Step 5: build Step for append ---
        step = Step(
            k=k,
            task_type=chain.task_type,
            thesis=proposed.content,
            thesis_prior=safe_prior,  # v0.9.1: store the guarded prior
            antitheses=antitheses,
            synthesis=synthesis_content,
            predicted_correct=computed_predicted,
            decision=decision,
            tokens=proposed.tokens + synth.tokens,
            timestamp=_utcnow_iso(),
        )
        return step

    def _persist_chain(self, chain: CoTChain) -> None:
        from ldd_trace.cot_memory import append_chain_trace, update_cot_memory

        append_chain_trace(self.store, chain)
        update_cot_memory(self.store)


def _utcnow_iso() -> str:
    return _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
