"""Property-based tests for the Metric Algebra — v0.9.0.

These tests go beyond fixed unit assertions: they establish ALGEBRAIC LAWS
over the composition operators + the normalization contracts. If an
implementation violates one of these properties for ANY input generated by
hypothesis, the test fails.

Laws proven here (each becomes a test):

  NORMALIZE
    1. Idempotency:     normalize(normalize(v)) == normalize(v)
    2. Bounded range:   normalize(v) ∈ [0, 1]  ∀v ∈ ℝ
    3. Monotonic (for bounded and positive, in valid domain)

  WEIGHTED SUM
    4. Bounded output:   ws ∈ [0, 1]
    5. Commutative in components (same weights)
    6. Linear in weights scaling (homogeneity):
       ws([m1, m2], [λw1, λw2])(x) == ws([m1, m2], [w1, w2])(x)
    7. Equal-weight weighted sum = arithmetic mean of normalized components
    8. Weight-0 component has no effect (degenerates to remaining sum)

  MAX / MIN
    9. Idempotency:  max(L, L) == L   and   min(L, L) == L
    10. Commutativity: max(L1, L2) == max(L2, L1)
    11. Duality relation:  max(L1, L2) + min(1-L1, 1-L2) ≡ 1  NOT strictly (uses inverted metrics)
        Simpler duality: max(normalized) ≥ min(normalized)  always
    12. max(single) == normalize(observed(single))

  BIAS-INVARIANCE (load-bearing)
    13. Memory-state-independence: calibrator.log() doesn't change metric.observed() output
        for any θ across all metrics registered.
    14. Spec-immutability: any mutation attempt on a registered spec raises

  GAMING-GUARD
    15. Any spec with self-referential description is rejected at construction
"""
from __future__ import annotations

import math
from pathlib import Path
from typing import List

import pytest

try:
    from hypothesis import assume, given, settings
    from hypothesis import strategies as st
except ImportError:
    pytest.skip("hypothesis not installed", allow_module_level=True)

from ldd_trace import TraceStore
from ldd_trace.metric import (
    GAMING_GUARD_PHRASES,
    BoundedRateMetric,
    MetricSpec,
    PositiveCountMetric,
    SignedDeltaMetric,
    bounded_rate,
    positive_count,
    signed_delta,
)
from ldd_trace.metric_compose import (
    MaxMetric,
    MinMetric,
    WeightedSumMetric,
    maximum,
    minimum,
    weighted_sum,
)
from ldd_trace.metric_registry import Calibrator, MetricRegistry


# Hypothesis strategies
floats_bounded = st.floats(min_value=0.0, max_value=1.0, allow_nan=False, allow_infinity=False)
floats_positive = st.floats(min_value=0.0, max_value=1e6, allow_nan=False, allow_infinity=False)
floats_signed = st.floats(
    min_value=-100.0, max_value=100.0, allow_nan=False, allow_infinity=False
)
weights_strategy = st.floats(
    min_value=0.001, max_value=100.0, allow_nan=False, allow_infinity=False
)


# ---------------------------------------------------------------------------
# NORMALIZE laws
# ---------------------------------------------------------------------------


class TestNormalizeProperties:
    @given(floats_bounded)
    def test_bounded_normalize_idempotent(self, v: float) -> None:
        m = bounded_rate("x", lambda o: (0, 1))
        once = m.normalize(v)
        twice = m.normalize(once)
        assert once == pytest.approx(twice)

    @given(st.floats(min_value=-1000.0, max_value=1000.0, allow_nan=False, allow_infinity=False))
    def test_bounded_normalize_stays_in_01(self, v: float) -> None:
        m = bounded_rate("x", lambda o: (0, 1))
        n = m.normalize(v)
        assert 0.0 <= n <= 1.0

    # NOTE: PositiveCount.normalize is NOT idempotent by design — its input
    # domain (raw [0,∞)) differs from its output range ([0,1]). Idempotency
    # is an algebraic law only of BoundedRate. For PositiveCount and
    # SignedDelta, we instead assert the stronger "output bounded in [0,1]"
    # and "monotonic non-decreasing within the non-saturated domain".

    @given(floats_positive)
    def test_positive_normalize_bounded(self, v: float) -> None:
        m = positive_count("x", lambda o: o, normalize_scale=100.0)
        n = m.normalize(v)
        assert 0.0 <= n <= 1.0

    @given(floats_signed)
    def test_signed_normalize_bounded(self, v: float) -> None:
        m = signed_delta("x", lambda o: o, normalize_scale=1.0)
        n = m.normalize(v)
        assert 0.0 <= n <= 1.0

    @given(floats_signed)
    def test_signed_normalize_zero_is_half(self, v: float) -> None:
        """normalize(0) must equal 0.5 (centered sigmoid)."""
        m = signed_delta("x", lambda o: o)
        assert m.normalize(0.0) == pytest.approx(0.5)

    @given(
        st.floats(min_value=-10.0, max_value=10.0, allow_nan=False, allow_infinity=False),
        st.floats(min_value=-10.0, max_value=10.0, allow_nan=False, allow_infinity=False),
    )
    def test_signed_normalize_monotonic_non_decreasing(
        self, a: float, b: float
    ) -> None:
        """For a ≤ b, normalize(a) ≤ normalize(b). (Non-decreasing is the
        strict guarantee — strict-less-than can fail at sigmoid saturation
        for |v| > ~30 due to float64 precision.)"""
        assume(a <= b)
        m = signed_delta("x", lambda o: o, normalize_scale=1.0)
        assert m.normalize(a) <= m.normalize(b) + 1e-12


# ---------------------------------------------------------------------------
# WEIGHTED SUM laws
# ---------------------------------------------------------------------------


class TestWeightedSumProperties:
    @given(floats_bounded, floats_bounded, weights_strategy, weights_strategy)
    def test_output_is_bounded_01(
        self, v1: float, v2: float, w1: float, w2: float
    ) -> None:
        m1 = bounded_rate("a", lambda o, x=v1: (x, 1))
        m2 = bounded_rate("b", lambda o, x=v2: (x, 1))
        ws = weighted_sum("ab", [(m1, w1), (m2, w2)])
        out = ws.observed(None)
        assert 0.0 <= out <= 1.0

    @given(floats_bounded, floats_bounded, weights_strategy, weights_strategy)
    def test_commutative_same_weights(
        self, v1: float, v2: float, w1: float, w2: float
    ) -> None:
        m1 = bounded_rate("a", lambda o, x=v1: (x, 1))
        m2 = bounded_rate("b", lambda o, x=v2: (x, 1))
        ws_ab = weighted_sum("ab", [(m1, w1), (m2, w2)])
        ws_ba = weighted_sum("ba", [(m2, w2), (m1, w1)])
        assert ws_ab.observed(None) == pytest.approx(ws_ba.observed(None))

    @given(
        floats_bounded, floats_bounded,
        weights_strategy, weights_strategy,
        st.floats(min_value=0.1, max_value=100.0, allow_nan=False, allow_infinity=False),
    )
    def test_homogeneous_in_weights(
        self, v1: float, v2: float, w1: float, w2: float, lam: float
    ) -> None:
        """Scaling all weights by λ does not change the output."""
        m1 = bounded_rate("a", lambda o, x=v1: (x, 1))
        m2 = bounded_rate("b", lambda o, x=v2: (x, 1))
        ws = weighted_sum("ab", [(m1, w1), (m2, w2)])
        ws_scaled = weighted_sum("ab2", [(m1, w1 * lam), (m2, w2 * lam)])
        assert ws.observed(None) == pytest.approx(ws_scaled.observed(None))

    @given(floats_bounded, floats_bounded)
    def test_equal_weights_is_mean(self, v1: float, v2: float) -> None:
        m1 = bounded_rate("a", lambda o, x=v1: (x, 1))
        m2 = bounded_rate("b", lambda o, x=v2: (x, 1))
        ws = weighted_sum("ab", [(m1, 1.0), (m2, 1.0)])
        assert ws.observed(None) == pytest.approx((v1 + v2) / 2)

    @given(floats_bounded, floats_bounded)
    def test_single_component_weighted_sum_is_identity(
        self, v1: float, _unused: float
    ) -> None:
        m1 = bounded_rate("a", lambda o, x=v1: (x, 1))
        ws = weighted_sum("a1", [(m1, 1.0)])
        assert ws.observed(None) == pytest.approx(v1)


# ---------------------------------------------------------------------------
# MAX / MIN laws
# ---------------------------------------------------------------------------


class TestMaxMinProperties:
    @given(floats_bounded)
    def test_max_idempotent(self, v: float) -> None:
        m = bounded_rate("x", lambda o, x=v: (x, 1))
        mx = maximum("x_max", [m, m])
        assert mx.observed(None) == pytest.approx(v)

    @given(floats_bounded)
    def test_min_idempotent(self, v: float) -> None:
        m = bounded_rate("x", lambda o, x=v: (x, 1))
        mn = minimum("x_min", [m, m])
        assert mn.observed(None) == pytest.approx(v)

    @given(floats_bounded, floats_bounded)
    def test_max_commutative(self, v1: float, v2: float) -> None:
        m1 = bounded_rate("a", lambda o, x=v1: (x, 1))
        m2 = bounded_rate("b", lambda o, x=v2: (x, 1))
        mx_ab = maximum("ab", [m1, m2])
        mx_ba = maximum("ba", [m2, m1])
        assert mx_ab.observed(None) == pytest.approx(mx_ba.observed(None))

    @given(floats_bounded, floats_bounded)
    def test_min_commutative(self, v1: float, v2: float) -> None:
        m1 = bounded_rate("a", lambda o, x=v1: (x, 1))
        m2 = bounded_rate("b", lambda o, x=v2: (x, 1))
        mn_ab = minimum("ab", [m1, m2])
        mn_ba = minimum("ba", [m2, m1])
        assert mn_ab.observed(None) == pytest.approx(mn_ba.observed(None))

    @given(floats_bounded, floats_bounded)
    def test_min_le_max(self, v1: float, v2: float) -> None:
        """min(L1, L2) ≤ max(L1, L2) for any values."""
        m1 = bounded_rate("a", lambda o, x=v1: (x, 1))
        m2 = bounded_rate("b", lambda o, x=v2: (x, 1))
        mn = minimum("x_min", [m1, m2])
        mx = maximum("x_max", [m1, m2])
        assert mn.observed(None) <= mx.observed(None) + 1e-9


# ---------------------------------------------------------------------------
# BIAS-INVARIANCE laws (load-bearing)
# ---------------------------------------------------------------------------


class TestBiasInvariance:
    def test_calibrator_log_does_not_mutate_metric_spec(
        self, tmp_path: Path
    ) -> None:
        """Logging calibration pairs must NOT change the metric's spec
        or the observed() output for any input."""
        store = TraceStore(tmp_path)
        reg = MetricRegistry(store)
        m = bounded_rate("m", lambda o: (o["x"], o["y"]))
        reg.register(m)
        cal = Calibrator(reg)

        # Observe a baseline
        original = m.observed({"x": 3, "y": 10})

        # Log many calibration pairs that would appear to "reward" high values
        for _ in range(20):
            cal.log("m", predicted=0.0, observed=1.0)

        # Observe must be unchanged
        assert m.observed({"x": 3, "y": 10}) == original
        # Spec must be unchanged
        assert reg.specs()["m"].version == m.spec.version
        assert reg.specs()["m"].advisory_only is True

    def test_promotion_does_not_change_observed(self, tmp_path: Path) -> None:
        """Even after a metric is promoted to load_bearing, observed()
        returns the same value for the same input."""
        store = TraceStore(tmp_path)
        reg = MetricRegistry(store)
        m = bounded_rate("m", lambda o: (o["x"], o["y"]))
        reg.register(m)
        cal = Calibrator(reg)

        original = m.observed({"x": 3, "y": 10})

        # Force a promotion by logging perfect calibration
        for _ in range(6):
            cal.log("m", 0.3, 0.3)
        assert cal.try_promote("m") is True

        # Observed is still the same
        assert m.observed({"x": 3, "y": 10}) == original

    def test_metric_spec_is_frozen(self) -> None:
        """Specs cannot be mutated after construction (frozen dataclass)."""
        s = MetricSpec(name="x", kind="bounded", unit="rate")
        with pytest.raises(Exception):
            s.version = 99  # type: ignore


# ---------------------------------------------------------------------------
# GAMING-GUARD laws
# ---------------------------------------------------------------------------


class TestGamingGuard:
    @given(st.sampled_from(list(GAMING_GUARD_PHRASES)))
    def test_any_self_ref_phrase_rejected(self, phrase: str) -> None:
        with pytest.raises(ValueError, match="gaming-guard"):
            MetricSpec(
                name="x",
                kind="bounded",
                unit="rate",
                description=f"this metric tracks {phrase} quality",
            )

    def test_neutral_descriptions_pass(self) -> None:
        """Descriptions about WHAT is measured (not about current action) pass."""
        MetricSpec(
            name="x", kind="bounded", unit="rate",
            description="fraction of failing assertions in the test suite",
        )
        MetricSpec(
            name="y", kind="positive", unit="ms",
            description="wall-clock latency from request to response",
        )
        MetricSpec(
            name="z", kind="signed", unit="dimensionless",
            description="delta between observed and predicted count",
        )


# ---------------------------------------------------------------------------
# Distribution-of-operators — verify output distributions are sane
# ---------------------------------------------------------------------------


class TestDistributionalProperties:
    @given(st.lists(floats_bounded, min_size=2, max_size=10))
    def test_max_equals_numpy_like_max_of_list(self, values: List[float]) -> None:
        """Our composite Max on N values agrees with builtin max."""
        metrics = [
            bounded_rate(f"m{i}", lambda o, x=v: (x, 1))
            for i, v in enumerate(values)
        ]
        mx = maximum("m_all", metrics)
        assert mx.observed(None) == pytest.approx(max(values))

    @given(st.lists(floats_bounded, min_size=2, max_size=10))
    def test_min_equals_numpy_like_min_of_list(self, values: List[float]) -> None:
        metrics = [
            bounded_rate(f"m{i}", lambda o, x=v: (x, 1))
            for i, v in enumerate(values)
        ]
        mn = minimum("m_all", metrics)
        assert mn.observed(None) == pytest.approx(min(values))


if __name__ == "__main__":
    import sys
    sys.exit(pytest.main([__file__, "-v"]))
